export const RoomIDs = {
    LINKS_HOUSE: {roomID: 0x04, name:"Link's House"},
    OUTSIDE_LINKS_HOUSE: {overworldID: 0x2C, name:"Outside Link's House"},
    OUTSIDE_HYRULE_CASTLE: {overworldID: 0x1B, name:"Outside Hyrule Castle"},
    UNCLE: {roomID: 0x55, quadV: 0x00, name:"Uncle"},
    PASSAGE_EXIT: {roomID: 0x55, quadV: 0x02, name:"Passage Exit"},
    CASTLE_LOBBY: {roomID: 0x61, name:"Castle Lobby"},
    SW_ROOM: {roomID: 0x60, name:"SW Room"},
    WEST_GUARD_HALLWAY: {roomID: 0x50, name:"West Guard Hallway"},
    STATUE_HALLWAY: {roomID: 0x01, name:"Statue Hallway"},
    FIRST_KEY_GUARD: {roomID: 0x72, quadH: 0x00, quadV: 0x00, name:"1st Key Guard"},
    B1_PIT_1: {roomID: 0x72, quadH: 0x00, quadV: 0x02, name:"B1 Pit 1"},
    B1_PIT_2: {roomID: 0x82, name:"B1 Pit 2"},
    STEALTH_ROOM: {roomID: 0x81, name:"Stealth Room"},
    GREEN_GUARD: {roomID: 0x71, quadH: 0x00, quadV: 0x02, name:"Green Guard"},
    BOOMERANG_GUARD: {roomID: 0x71, quadH: 0x01, quadV: 0x02, name:"Boomerang Guard"},
    STAIRS_TO_B2: {roomID: 0x71, quadH: 0x00, quadV: 0x00, name:"Stairs to B2"},
    B2: {roomID: 0x70, name:"B2"},
    BALL_N_CHAIN: {roomID: 0x80, name:"Ball N' Chain"},
    THRONE_ROOM: {roomID: 0x51, name:"Throne Room"},
    SEWER_PASSAGE: {roomID: 0x41, name:"Sewer Passage"},
    SNAKE_ROOM: {roomID: 0x42, name:"Snake Room"},
    SEWER_KEY_CHEST: {roomID: 0x32, quadH: 0x01, quadV: 0x00, name:"Sewer Key Chest"},
    SEWER_1: {roomID: 0x22, name:"Sewer 1"},
    SEWER_2: {roomID: 0x21, quadH: 0x01, quadV: 0x02, name:"Sewer 2"},
    KEY_RAT: {roomID: 0x21, quadH: 0x00, quadV: 0x00, name:"Key Rat"},
    RAT_HALLWAY: {roomID: 0x11, name:"Rat Hallway"},
    BEHIND_SANCTUARY_1: {roomID: 0x02, quadH: 0x01, quadV: 0x00, name:"Behind Sanctuary 1"},
    BEHIND_SANCTUARY_2: {roomID: 0x02, quadH: 0x00, quadV: 0x02, name:"Behind Sanctuary 2"},
    SANCTUARY: {roomID: 0x12, name:"Sanctuary"},
}